print("Content-Type: text/html")
print()
print("<!DOCTYPE HTML>")
print("<html>")
print("<head>")
print("<title>Hello World!</title>")
print("</head>")
print("<body>")
print("<h1>Hello World! This is me</h1>")
print("<h2>I am learning HTML today</h2>")
print("</body>")
print("</html>")